export const CONFIRM_EMAIL_PENDING = 'email/CONFIRM_EMAIL_PENDING';
export const CONFIRM_EMAIL_SUCCESS = 'email/CONFIRM_EMAIL_SUCCESS';
export const CONFIRM_EMAIL_FAILURE = 'email/CONFIRM_EMAIL_FAILURE';
