export const CLEAR_AUTH = 'auth/CLEAR_AUTH';
export const CLEAR_AUTH_ERRORS = 'auth/CLEAR_AUTH_ERRORS';
export const REQUEST_AUTH_FAILURE = 'auth/REQUEST_AUTH_FAILURE';
export const REQUEST_AUTH_PENDING = 'auth/REQUEST_AUTH_PENDING';
export const REQUEST_AUTH_SUCCESS = 'auth/REQUEST_AUTH_SUCCESS';
