export const TYPES = {
  AuthService: Symbol('AuthService'),
  BlobStorage: Symbol('BlobStorage'),
  Cache: Symbol('Cache'),
  Config: Symbol('Config'),
  Db: Symbol('Db'),
  HealthCheckerService: Symbol('HealthCheckerService'),
  Logger: Symbol('Logger'),
  Mailer: Symbol('Mailer'),
  NotationLoader: Symbol('NotationLoader'),
  NotationRepo: Symbol('NotationRepo'),
  NotationService: Symbol('NotationService'),
  NotificationService: Symbol('NotificationService'),
  TaggingRepo: Symbol('TaggingRepo'),
  TaggingService: Symbol('TaggingService'),
  TagLoader: Symbol('TagLoader'),
  TagRepo: Symbol('TagRepo'),
  TagService: Symbol('TagService'),
  UserLoader: Symbol('UserLoader'),
  UserRepo: Symbol('UserRepo'),
  UserService: Symbol('UserService'),
  VideoUrlService: Symbol('VideoUrlService'),
  MessageQueue: Symbol('MessageQueue'),
};
