export const TYPES = {
  ApiServer: Symbol('ApiServer'),
  AssociateVideoUrl: Symbol('AssociateVideoUrl'),
  AuthService: Symbol('AuthService'),
  BlobStorage: Symbol('BlobStorage'),
  Cache: Symbol('Cache'),
  Config: Symbol('Config'),
  Db: Symbol('Db'),
  HealthCheckerService: Symbol('HealthCheckerService'),
  Logger: Symbol('Logger'),
  Mailer: Symbol('Mailer'),
  MailWriterService: Symbol('MailWriterService'),
  MessageQueue: Symbol('MessageQueue'),
  NotationRepo: Symbol('NotationRepo'),
  NotationService: Symbol('NotationService'),
  PulseCheck: Symbol('PulseCheck'),
  Redis: Symbol('Redis'),
  SendMail: Symbol('SendMail'),
  NotationTagRepo: Symbol('NotationTagRepo'),
  NotationTagService: Symbol('NotationTagService'),
  TagRepo: Symbol('TagRepo'),
  TagService: Symbol('TagService'),
  UserRepo: Symbol('UserRepo'),
  UserService: Symbol('UserService'),
  VideoUrlService: Symbol('VideoUrlService'),
  VideoInfoService: Symbol('VideoInfoService'),
  WorkerServer: Symbol('WorkerServer'),
};
