import { configFactory } from './configFactory';
import {
  APP_GRAPHQL_PORT,
  APP_SESSION_SECRET,
  APP_WEB_ORIGIN,
  AWS_ACCESS_KEY_ID,
  AWS_REGION,
  AWS_SECRET_ACCESS_KEY,
  CDN_DOMAIN_NAME,
  DB_HOST,
  DB_NAME,
  DB_PASSWORD,
  DB_PORT,
  DB_USERNAME,
  DEV_EMAIL,
  INFO_EMAIL,
  LOG_LEVEL,
  NODE_ENV,
  REDIS_HOST,
  REDIS_PORT,
  S3_BUCKET,
  S3_VIDEO_SRC_BUCKET,
  SQS_VIDEO_QUEUE_URL,
} from './constants';

export const getServerConfig = configFactory({
  NODE_ENV: NODE_ENV,
  LOG_LEVEL: LOG_LEVEL,
  APP_GRAPHQL_PORT: APP_GRAPHQL_PORT,
  APP_SESSION_SECRET: APP_SESSION_SECRET,
  APP_WEB_ORIGIN: APP_WEB_ORIGIN,
  AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID,
  AWS_REGION: AWS_REGION,
  AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY,
  CDN_DOMAIN_NAME: CDN_DOMAIN_NAME,
  S3_BUCKET: S3_BUCKET,
  S3_VIDEO_SRC_BUCKET: S3_VIDEO_SRC_BUCKET,
  SQS_VIDEO_QUEUE_URL: SQS_VIDEO_QUEUE_URL,
  INFO_EMAIL: INFO_EMAIL,
  DEV_EMAIL: DEV_EMAIL,
  DB_HOST: DB_HOST,
  DB_NAME: DB_NAME,
  DB_PASSWORD: DB_PASSWORD,
  DB_PORT: DB_PORT,
  DB_USERNAME: DB_USERNAME,
  REDIS_HOST: REDIS_HOST,
  REDIS_PORT: REDIS_PORT,
});

export type ServerConfig = ReturnType<typeof getServerConfig>;

export const getJobConfig = configFactory({});

export type JobConfig = ReturnType<typeof getJobConfig>;
