export enum HttpStatus {
  OK = 200,
  INTERNAL_SERVER_ERROR = 500,
}

export enum ErrorCode {
  UNKNOWN = 'UNKNOWN',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  INVALID = 'INVALID',
  BAD_REQUEST = 'BAD_REQUEST',
  NOT_FOUND = 'NOT_FOUND',
  INTERNAL = 'INTERNAL',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
}
