export const TYPES = {
  AuthClient: Symbol('AuthClient'),
  AuthResolver: Symbol('AuthResolver'),
  AuthService: Symbol('AuthService'),
  ContainerConfig: Symbol('ContainerConfig'),
  Fetch: Symbol('Fetch'),
  GraphqlClient: Symbol('GraphqlClient'),
  GraphqlServerUri: Symbol('GraphqlServerUri'),
  HealthCheckerService: Symbol('HealthCheckerService'),
  HealthController: Symbol('HealthController'),
  NotationModel: Symbol('NotationModel'),
  NotationRepo: Symbol('NotationRepo'),
  NotationSequelizeRepo: Symbol('NotationSequelizeRepo'),
  NotationService: Symbol('NotationService'),
  NotificationService: Symbol('NotificationService'),
  Redis: Symbol('Redis'),
  ReqId: Symbol('ReqId'),
  Sequelize: Symbol('Sequelize'),
  TagModel: Symbol('TagModel'),
  TagRepo: Symbol('TagRepo'),
  TagSequelizeRepo: Symbol('TagSequelizeRepo'),
  TagService: Symbol('TagService'),
  UserModel: Symbol('UserModel'),
  UserRepo: Symbol('UserRepo'),
  UserResolver: Symbol('UserResolver'),
  UserSequelizeRepo: Symbol('UserSequelizeRepo'),
  UserService: Symbol('UserService'),
};
