export const TYPES = {
  AuthResolver: Symbol('AuthResolver'),
  AuthClient: Symbol('AuthClient'),
  AuthService: Symbol('AuthService'),
  ContainerConfig: Symbol('ContainerConfig'),
  Fetch: Symbol('Fetch'),
  GraphqlClient: Symbol('GraphqlClient'),
  GraphqlServerUri: Symbol('GraphqlServerUri'),
  HealthCheckerService: Symbol('HealthCheckerService'),
  HealthController: Symbol('HealthController'),
  NotificationService: Symbol('NotificationService'),
  NotationModel: Symbol('NotationModel'),
  Redis: Symbol('Redis'),
  Sequelize: Symbol('Sequelize'),
  TagModel: Symbol('TagModel'),
  UserModel: Symbol('UserModel'),
  UserRepo: Symbol('UserRepo'),
  UserResolver: Symbol('UserResolver'),
  UserService: Symbol('UserService'),
};
